// app
export const SYNC_STATE_FROM_STORAGE = 'SYNC_STATE_FROM_STORAGE';
export const GET_SYSTEM_MENUS = 'GET_SYSTEM_MENUS';
export const SET_ACTIVE_SYSTEM_MENU_INDEX = 'SET_ACTIVE_SYSTEM_MENU_INDEX';
export const SET_BREADCRUMB = 'SET_BREADCRUMB';
export const SET_PAGE_TITLE = 'SET_PAGE_TITLE';

// hello
export const GET_USER = 'GET_USER';
export const CHANGE_HELLO_MESSAGE = 'CHANGE_HELLO_MESSAGE';
